#!/bin/bash

clear
read -p "What process regex? " regex
echo "Waiting..."

process="$(ps aux | grep -P "$regex" | grep -Pv 'grep')"

while [[ "$process" != "" ]]; do
	sleep 1m
	process="$(ps aux | grep -P "$regex" | grep -Pv 'grep')"
done

# if headphones are unpluged (https://askubuntu.com/questions/133809/mute-sound-on-headphone-unplug)
if [[ "$(cat '/proc/asound/card0/codec#0' | head -n 140 | tail -n 1 | grep -Po 'OUT')" == "OUT" ]]; then
	mpv ~/Música/bash/alarmProcess.mp3 &> /dev/null &
else
	mpv --volume 50 ~/Música/bash/alarmProcess.mp3 &> /dev/null &
fi
read -p "Press enter to continue -> "
kill $!
