#!/bin/bash

# It is neccesary acpid

if [[ "$(ps aux | grep -P acpi_listen | grep -Pv 'grep')" == "" ]]; then
	systemctl start acpid.service
	acpi_listen | grep -Pi 'headphone' > ~/tmp/headphonesStatus &
fi

playMusic () {
	if [[ "$(cat ~/tmp/headphonesStatus | tail -n 1 | grep -P 'unplug')" != "" ]]; then
		mpv ~/Música/bash/alarmProcess.mp3 &> /dev/null &
	else
		mpv --volume 50 ~/Música/bash/alarmProcess.mp3 &> /dev/null &
	fi
}

clear
read -p "What process regex? " regex
echo "Waiting..."

process="$(ps aux | grep -P "$regex" | grep -Pv 'grep')"

while [[ "$process" != "" ]]; do
	sleep 1m
	process="$(ps aux | grep -P "$regex" | grep -Pv 'grep')"
done

playMusic
read -p "Press enter to continue -> "
kill $!
